### ISSUE TITLE
Error using Alloy and prebuild Titanium SDK 3.4.2

### ISSUE THREAD

**Issue by IonRod** [mokesmokes/titanium-android-facebook#10]
I've got that error using Alloy. Could you help with the solution?

The code (index.js):

//------------------------------------

var _fb = require('com.ti.facebook');

(function init() {
	$.win.fbProxy = _fb.createActivityWorker({lifecycleContainer: $.win});
	$.win.open();
})();

//------------------------------------

Error:

[ERROR] :  TiBaseActivity: (main) [0,14992] Error dispatching lifecycle event: null
[ERROR] :  TiBaseActivity: java.lang.NullPointerException
[ERROR] :  TiBaseActivity: 	at com.ti.facebook.ActivityWorkerProxy.onResume(ActivityWorkerProxy.java:76)
[ERROR] :  TiBaseActivity: 	at org.appcelerator.titanium.TiLifecycle.fireLifecycleEvent(TiLifecycle.java:140)
[ERROR] :  TiBaseActivity: 	at org.appcelerator.titanium.TiBaseActivity.onResume(TiBaseActivity.java:1119)
[ERROR] :  TiBaseActivity: 	at org.appcelerator.titanium.TiActivity.onResume(TiActivity.java:35)
[ERROR] :  TiBaseActivity: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1209)
[ERROR] :  TiBaseActivity: 	at android.app.Activity.performResume(Activity.java:5450)
[ERROR] :  TiBaseActivity: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2909)
[ERROR] :  TiBaseActivity: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2948)
[ERROR] :  TiBaseActivity: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
[ERROR] :  TiBaseActivity: 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] :  TiBaseActivity: 	at android.os.Looper.loop(Looper.java:176)
[ERROR] :  TiBaseActivity: 	at android.app.ActivityThread.main(ActivityThread.java:5419)
[ERROR] :  TiBaseActivity: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiBaseActivity: 	at java.lang.reflect.Method.invoke(Method.java:525)
[ERROR] :  TiBaseActivity: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
[ERROR] :  TiBaseActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
[ERROR] :  TiBaseActivity: 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mokesmokes** [comment]
Are you using my 3_4_M branch? It will not work with Titanium's standard 3.4.2 or 3.5.0.GA, the first standard Titanium release which will work with this module is 3.6.0

**Comment by IonRod** [comment]
Yes, I'm using your prebuild 3.4.2 SDK.

By the way, my do not crashes, just got that error when resuming to activity. If I use official SDK it crashes on start.

**Comment by mokesmokes** [comment]
Can you share a zip file of a test project which fails like this?

**Comment by IonRod** [comment]
Yes of course:
https://dl.dropboxusercontent.com/u/41255008/bug.zip
Here you can get test project.

You could ask me in Skype:
rod.ion.

I'll try to help if I could.

**Comment by IonRod** [comment]
You should test on real device. I've got that bug on Android 4.3 and Android 4.4 on Galaxy S3.

**Comment by mokesmokes** [comment]
I tried on 4.4.4 emulator as well as Galaxy S4 with 4.4.2. I even downloaded again the SDK zip file, just to make sure. It works fine for me with no issues. BTW - your TiApp.xml was incorrect, that was the only thing that needed fixing. Here is the relevant section, fixed (the manifest node needs to enclose the application node):
```
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="806" android:versionName="0.8.6">
            <application>
                <meta-data android:name="LOCALYTICS_APP_KEY" android:value="d376854342f01df46e5a864-55130b90-8225-11e4-293d-004a77f8b47f"/>
                <activity android:label="2for1"
                    android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
                <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/app_id"/>
            </application>
        </manifest>
    </android>
```

**Comment by IonRod** [comment]
THANK YOU!

The problem was with manifest and with
	_fb.permissions = ['public_profile', 'email', 'user_friends'];
	_fb.initialize(5000);

Thought it is not important if I don't want to use login throught fb

**Comment by sphairo** [comment]
@IonRod I need you help!

Error dispatching lifecycle event: null 

[ERROR] : TiBaseActivity: java.lang.NullPointerException
[ERROR] : TiBaseActivity: at facebook.ActivityWorkerProxy.onResume(ActivityWorkerProxy.java:79)
[ERROR] : TiBaseActivity: at org.appcelerator.titanium.TiLifecycle.fireLifecycleEvent(TiLifecycle.java:150)
[ERROR] : TiBaseActivity: at org.appcelerator.titanium.TiBaseActivity.onResume(TiBaseActivity.java:1130)
[ERROR] : TiBaseActivity: at org.appcelerator.titanium.TiActivity.onResume(TiActivity.java:35)
[ERROR] : TiBaseActivity: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1215)
[ERROR] : TiBaseActivity: at android.app.Activity.performResume(Activity.java:5327)
[ERROR] : TiBaseActivity: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2797)
[ERROR] : TiBaseActivity: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2845)
[ERROR] : TiBaseActivity: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
[ERROR] : TiBaseActivity: at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] : TiBaseActivity: at android.os.Looper.loop(Looper.java:136)
[ERROR] : TiBaseActivity: at android.app.ActivityThread.main(ActivityThread.java:5086)
[ERROR] : TiBaseActivity: at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] : TiBaseActivity: at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] : TiBaseActivity: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] : TiBaseActivity: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] : TiBaseActivity: at dalvik.system.NativeStart.main(Native Method)
