### ISSUE TITLE
Failure to capture events after fb.authorize()

### ISSUE THREAD

**Issue by JeffKitson** [mokesmokes/titanium-android-facebook#11]
I've reviewed the docs, your commits, and the other issues at length trying to make sure this isn't something obvious. It seems the event listeners assigned to the proxy never fire. Neither success, fail, cancel or other gets tripped.

I'm using the custom 3.4.2 branch you listed and create it like so below:

```javascript
var win1 = Ti.UI.createWindow({
		backgroundColor:'white'
	});
	var fb = require('com.ti.facebook');
	 win1.fbProxy = fb.createActivityWorker({lifecycleContainer: win1});
	fb.permissions = ['public_profile', 'email', 'user_friends'];
	// now set up listeners
	fb.addEventListener('login', function(e) {
    if(e.success) {

```
All of the ux and authentication process seems just fine but for some odd reason the result events aren't picked up. I know you do presence testing for the listener so I tried assigning the listener to both win1, fb, and win1.fbProxy but I always got the same result.

```log
[INFO] :   chromium: [INFO:library_loader_hooks.cc(112)] Chromium logging enabled: level = 0, default verbosity = 0
[INFO] :   BrowserProcessMain: Initializing chromium process, renderers=0
[WARN] :   chromium: [WARNING:proxy_service.cc(888)] PAC support disabled because there is no system implementation
[INFO] :   Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
[INFO] :   chromium: [INFO:simple_index_file.cc(397)] Simple Cache Index is being restored from disk.
[ERROR] :  ViewRootImpl: sendUserActionEvent() mView == null
[INFO] :   chromium: [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
[INFO] :   chromium: [INFO:async_pixel_transfer_manager_android.cc(56)] Async pixel transfers not supported
[ERROR] :  qdutils: FBIOGET_FSCREENINFO failed
[ERROR] :  ViewRootImpl: sendUserActionEvent() mView == null
[ERROR] :  ViewRootImpl: sendUserActionEvent() mView == null
[INFO] :   APSAnalyticsService: Analytics Service Started
[INFO] :   APSAnalyticsService: Stopping Analytics Service
```

Thanks for building these modules btw.

**Comment by mokesmokes** [comment]
Did you call `fb.initialize()` (just once in your app) after setting up your listeners?

**Comment by JeffKitson** [comment]
I call 
```javascript
fb.initialize(0); // the module will do nothing prior to this. This enabled you to set up listeners anywhere in the app  
	                     // You can (and should) pass a timeout (in ms) for the /me request that occurs upon login,
	                     // the default value is 0 (no timeout)
	
	if (!fb.loggedIn) {
	    // you want to show your login UI in this case
	    // if the user is loggedIn, just wait for the login event
	    // when you want the user to login, call fb.authorize()
	}
	
	
	    fb.authorize(); // this will show the Facebook login UI;
```
This code is right after the close of the listener from my earlier snippet . Thanks for the reply.

**Comment by mokesmokes** [comment]
Do you see the Facebook login UI after calling fb.authorize?

**Comment by JeffKitson** [comment]
Oh yea. Makes it all the way through the auth process with Facebook and it works as expected until it closes out after the user authorizes the application. Facebook shows the app as authorized but I can never get any of the events coming from the module. I'm not sure if there is something else I'd need that would cause this issue. As I mentioned I'm using your branch of the SDK and the module.

**Comment by mokesmokes** [comment]
I suggest you post a complete failing project on Dropbox

**Comment by mokesmokes** [comment]
Closing due to no reply. Events work in a properly implemented app, as attested by numerous developers.

**Comment by mokesmokes** [comment]
See the [sample app](https://github.com/mokesmokes/facebook-titanium-sample)
