### ISSUE TITLE
The minimum required SDK version is 3.6.0?

### ISSUE THREAD

**Issue by gstreetmedia** [mokesmokes/titanium-android-facebook#13]
It's unclear to me what version of the SDK must be used to get this module to work. Documentation calls for 3.6.0. Is this now version 4.0 (master)? The highest available in Tags is 3.5.1.  Does this contain the required merges (or some fix) for the issues outlined in the example app (lifecycleContainer)?

https://github.com/appcelerator/titanium_mobile/pull/6272
https://github.com/appcelerator/titanium_mobile/pull/6275

I always build a custom version of TI for Android, as I need patches to TiView to make my app work properly. So I'm trying to determine what tag, or branch is the starting point.

Thanks!

**Comment by mokesmokes** [comment]
You need those PRs which were backported a few hours ago to 3_5_X: https://github.com/appcelerator/titanium_mobile/pull/6650 :)
So use Appcelerator's 3_5_X with latest updates (recommended), or master (too unstable at this point, in my opinion)

**Comment by mobilebanzai** [comment]
So is the official 3.5.1.GA SDK compatible with your latest Android module?

**Comment by gstreetmedia** [comment]
It did work just fine with the pre 3.5.1ga
