### ISSUE TITLE
Your app must not use a Facebook Web Dialog

### ISSUE THREAD

**Issue by vivekgidmare** [mokesmokes/titanium-android-facebook#15]
Hi,

This what Facebook say when we submit app for review to access extra permissions[user_birthday
user_location]

_"Your app must not use a Facebook Web Dialog. Utilize our native Facebook Login SDK for iOS, so that users do not need to login twice."_

**Comment by mokesmokes** [comment]
I don't see how this is related to the module. My app passed Facebook review for additional permissions for both iOS and Android. Something is off in your implementation.

**Comment by mokesmokes** [comment]
In any case, my module has been adopted by Appcelerator, so please turn to the Q&A for support. https://github.com/appcelerator-modules/ti.facebook
