### ISSUE TITLE
Share dialog not working as expected

### ISSUE THREAD

**Issue by skypanther** [mokesmokes/titanium-android-facebook#9]
I'm attempting to use the Share dialog to share an open graph story. I have defined the story and objects in my Facebook app's control panel. I've followed the tips you [shared here](http://developer.appcelerator.com/question/180011/share-dialog-example-for-mokesmokes-facebook-module#comment-223334)

```javascript
if(win.fb.canPresentShareDialog) {
  win.fb.share({
    url: 'http://example.com', 
    namespaceObject: 'myapp:Myobject',
    objectName: "Myobject", 
    imageUrl: 'https://s3.amazonaws.com/foo/bar.png', 
    title: 'My Title', 
    description: "My wonderful description", 
    namespaceAction: "myapp:Share" 
  });
}
```

If I include the `namespaceObject` attribute, the share dialog opens then immediately closes. However, in that brief moment it's open the title, image, and description can be seen in the share dialog.

If I leave out the `namespaceObject` property, I get an empty story screen as shown attached. It includes only details as defined in my Facebook settings page.

It would seem that namespaceAction, namespaceObject, and object are case-sensitive. Using lowercase results in no details in the share dialog (just those from the app settings page).

I have yet to try this on iOS. But that's next on my to-do list.

![device-2015-01-07-213214](https://cloud.githubusercontent.com/assets/507996/5657157/a7b21ee4-96b7-11e4-8beb-1c7f142c6ad3.png)

**Comment by mokesmokes** [comment]
You should make sure all your Facebook settings are in order, e.g. http://stackoverflow.com/questions/21182939/android-facebook-open-graph-share-dialog-opens-then-crashes

**Comment by mokesmokes** [comment]
And what do the device logs say? I'm guessing the Facebook app logs something in this case.

**Comment by skypanther** [comment]
Thanks. I'll check the logs & try the hash key, though their docs say the following which would lead me to believe that during testing this wouldn't be required.

>"To authenticate the exchange of information between your app and the Facebook, you need to generate a release key hash and add this to the Android settings within your Facebook App ID. Without this, your Facebook integration may not work properly **when you release your app to the store**."

(emphasis mine)

**Comment by skypanther** [comment]
I am seeing messages that indicate this is a problem with key hashes as you suggested. But I'm stumped. This is in my logs:

```shell
com.facebook.http.protocol.ApiException: [code] 404 [message]: (#404) Key hash zON/CPoDnIgHvMure4hh9HWdR58 does not match any stored key hashes. [extra]: 
```

However, that doesn't match the development keystore's hash that I extract from the SDK (using your 3.4.2 build), which is xSLzBBuLJunOQPB89rtzM54FXx4=

```shell
keytool -exportcert -alias androiddebugkey -keystore "/Users/timpoulsen/Library/Application Support/Titanium/mobilesdk/osx/3.4.2.MOKESMOKES/android/dev_keystore" | openssl sha1 -binary | openssl base64
```

I'm sure that's the keystore being used to sign the APK (I grabbed the path from the build log output). Where's the hash that's showing up in the logs (and presumably being sent to FB) coming from if not from my signing keystore as their docs state? 

I have tried entering my actual extracted hash into both the https://developers.facebook.com/settings/developer/sample-app/ page as well as under the Release hashes on the app's settings page and get the same results. I've also added the hash that's shown in the logs (I had to append a `=` to make it valid) to both those settings pages. However, the share dialog still opens & immediately closes. Perhaps there's some delay, but I entered the hashes over an hour ago and still have the same open-close problem and the same message is appearing the logs.

**Comment by mokesmokes** [comment]
@skypanther I think you have the export command wrong. You need to set -alias tidev -storepass tirocks and not androiddebugkey - this is the development key for Ti SDKs.

**Comment by skypanther** [comment]
Oh my. Obviously I copy & pasted their command and didn't update it properly. Maybe I should see if McDonalds has any openings ... 

For anyone who reads this later, and can read past my beginner-level mistakes, I did find another cause of the open, immediate-close behavior. My objects are named in the FB control panel with the first letter capitalized (Myobject) and actions are likewise lead-capped. In my code, I therefore tried `objectName: Myobject` and `namespaceAction: "myapp:Share"`. This is wrong. At least for me, they needed to be lowercase in my code:  `objectName: myobject` and `namespaceAction: "myapp:share"`

**Comment by mokesmokes** [comment]
Indeed all of Facebook's examples are in lower case. And to be honest - been there done that.... I've made all of these mistakes myself too, and I think Facebook could definitely simplify things....
